CREATE DATABASE IF NOT EXISTS Congreso;
USE Congreso;

CREATE TABLE PARTICIPANTE (
    CLAVE_PART INT NOT NULL,
    NOM VARCHAR(45),
    AP_PAT VARCHAR(45),
    AP_MAT VARCHAR(45),
    INST VARCHAR(45),
    TIPO_PART VARCHAR(45),
    NACIONALIDAD VARCHAR(45),
    DIR VARCHAR(45),
    PRIMARY KEY (CLAVE_PART)
);

CREATE TABLE TALLER (
    `CLAVE INT` INT NOT NULL, 
    NOMBRE VARCHAR(45),
    COSTO FLOAT,
    FECHA_INI DATE,
    FECHA_FIN DATE,
    PRIMARY KEY (`CLAVE INT`)
);

CREATE TABLE ARTICULOS (
    CLAVE_ART INT NOT NULL,
    TITULO VARCHAR(45),
    PRIMARY KEY (CLAVE_ART)
);

CREATE TABLE AUTORES (
    idAutor INT NOT NULL,
    NOMBRE VARCHAR(45),
    CORREO VARCHAR(45),
    GRADO VARCHAR(45),
    PRIMARY KEY (idAutor)
);

-- 2. Tablas con llaves foráneas directas
CREATE TABLE CONFERENCIA (
    CLAVE_CONF INT NOT NULL,
    COSTO FLOAT,
    FECHA DATE,
    ARTICULOS_CLAVE_ART INT NOT NULL UNIQUE,
    PRIMARY KEY (CLAVE_CONF),
    FOREIGN KEY (ARTICULOS_CLAVE_ART) REFERENCES ARTICULOS(CLAVE_ART)
);

CREATE TABLE INSTRUCTOR (
    idInstructor INT NOT NULL,
    NOM VARCHAR(45),
    INSTITUCION VARCHAR(45),
    GRADO VARCHAR(45),
    `TALLER_CLAVE INT` INT NOT NULL,
    PRIMARY KEY (idInstructor),
    FOREIGN KEY (`TALLER_CLAVE INT`) REFERENCES TALLER(`CLAVE INT`)
);

CREATE TABLE PARTICIPANTE_CONFERENCIA (
    CONFERENCIA_CLAVE_CONF INT NOT NULL,
    PARTICIPANTE_CLAVE_PART INT NOT NULL,
    PRIMARY KEY (CONFERENCIA_CLAVE_CONF, PARTICIPANTE_CLAVE_PART),
    FOREIGN KEY (CONFERENCIA_CLAVE_CONF) REFERENCES CONFERENCIA(CLAVE_CONF),
    FOREIGN KEY (PARTICIPANTE_CLAVE_PART) REFERENCES PARTICIPANTE(CLAVE_PART)
);

CREATE TABLE PARTICIPANTE_TALLER (
    PARTICIPANTE_CLAVE_PART INT NOT NULL,
    `TALLER_CLAVE INT` INT NOT NULL,
    PRIMARY KEY (PARTICIPANTE_CLAVE_PART, `TALLER_CLAVE INT`),
    FOREIGN KEY (PARTICIPANTE_CLAVE_PART) REFERENCES PARTICIPANTE(CLAVE_PART),
    FOREIGN KEY (`TALLER_CLAVE INT`) REFERENCES TALLER(`CLAVE INT`)
);

CREATE TABLE AUTORES_ARTICULOS (
    AUTORES_idAutor INT NOT NULL,
    ARTICULOS_CLAVE_ART INT NOT NULL,
    PRIMARY KEY (AUTORES_idAutor, ARTICULOS_CLAVE_ART),
    FOREIGN KEY (AUTORES_idAutor) REFERENCES AUTORES(idAutor),
    FOREIGN KEY (ARTICULOS_CLAVE_ART) REFERENCES ARTICULOS(CLAVE_ART)
);